#!/usr/bin/zsh

battery_state=$(cat /sys/class/power_supply/BAT0/status)
battery_capacity=$(cat /sys/class/power_supply/BAT0/capacity)
battery_percentage=$battery_capacity'%'

echo 🔋 $battery_percentage
